### ISSUE TITLE
Missing data for UT1 to UT5 sensors

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#71] opened 2015-12-01 09:53 UTC
When looking at temperature and pressure timelines pressure is missing for the mentioned sensors. Have a look at the attached screenshot.

![chart](https://cloud.githubusercontent.com/assets/1506876/11497502/b643d04c-9819-11e5-95ba-62713f3f26d8.png)

**Comment by nowakowski** [comment] 2015-12-01 15:10
@dharezlak Unable to reproduce. I just checked - the data is present in the database, correctly returned via API call and correctly visualized in the UI. See attached screenshot (from production UI).
![dap_scrn](https://cloud.githubusercontent.com/assets/4568385/11504488/f4152804-9845-11e5-8192-35d0c0c416a6.png)

**Comment by dharezlak** [comment] 2015-12-01 17:39
Indeed, now it looks much better. However UT4 still shows some incoherency:

![chart](https://cloud.githubusercontent.com/assets/1506876/11508779/c9cafe60-985a-11e5-845b-082437b6e4cd.png)

**Comment by nowakowski** [comment] 2015-12-02 08:31
No readings for UT4_T are being received from MOM. Perhaps the sensor is malfunctioning. We have notified Marek Konieczny.

**Comment by nowakowski** [comment] 2015-12-18 11:42
Marek Konieczny informs us that no data for this sensor is being sent by the Budokop infrastructure and that he has notified them of the issue.

**Comment by nowakowski** [comment] 2015-12-18 12:29
Update: the sensor malfunctioned and will be replaced during the Christmas break. Closing issue.

**Closed by nowakowski** 2015-12-18 12:29 UTC
Labels: help wanted
