### ISSUE TITLE
Unable to get fibre readings for concrete point in time (504 status response)

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#77] opened 2016-01-04 07:47 UTC
While asking about fibre data:

```
/api/v1/measurements?timeline_id=471%2C476%2C477%2C481%2C482%2C493%2C494%2C495%2C496%2C497%2C501%2C508%2C509%2C510%2C518%2C519%2C520%2C530%2C531%2C532%2C533%2C534%2C550%2C551%2C552%2C553%2C554%2C555%2C556%2C557%2C563%2C564%2C581%2C582%2C583%2C584%2C585%2C586%2C587%2C588%2C589%2C599%2C600%2C601%2C602%2C615%2C616%2C617%2C618%2C619%2C620%2C621%2C622%2C623%2C624%2C625%2C626%2C627%2C628%2C629%2C630%2C631%2C632%2C633%2C634%2C635%2C636%2C637%2C638%2C639%2C640%2C641%2C642%2C643%2C644%2C645%2C646%2C647%2C648%2C649%2C650%2C651%2C652%2C653%2C654%2C655%2C656%2C657%2C658%2C659%2C660%2C661%2C662%2C663%2C664%2C665%2C666%2C667%2C668%2C669%2C670%2C671%2C672%2C673%2C674%2C675%2C676%2C677%2C678%2C679%2C680%2C681%2C682%2C683%2C684%2C685%2C686%2C687%2C688%2C689%2C690%2C691%2C696%2C699%2C701%2C702%2C703%2C704%2C705%2C706%2C707%2C708%2C709%2C710%2C711%2C712%2C713%2C714%2C715%2C716%2C717%2C718%2C719%2C720%2C721%2C722%2C723%2C724%2C725%2C726%2C727%2C728%2C729%2C730%2C731%2C732%2C733%2C734%2C735%2C736%2C737%2C738%2C739%2C740%2C741%2C742%2C743%2C744%2C745%2C746%2C747%2C748%2C749%2C750%2C751%2C752%2C753%2C754%2C755%2C756%2C757%2C758%2C759%2C760%2C761%2C762%2C763%2C764%2C765%2C766%2C767%2C768%2C769%2C770%2C771%2C772%2C773%2C774%2C775%2C776%2C777%2C778%2C779%2C780%2C781%2C782%2C783%2C784%2C785%2C786%2C787%2C788%2C789%2C790%2C791%2C792%2C793%2C794%2C795%2C796%2C797%2C798%2C799%2C800%2C801%2C802%2C803%2C804%2C805%2C806%2C808%2C809%2C810%2C811%2C812%2C814%2C816%2C817%2C818%2C819%2C820%2C821%2C822%2C823%2C824%2C825%2C826%2C827%2C828%2C829%2C830%2C831%2C832%2C833%2C834%2C835%2C836%2C837%2C838%2C839%2C840%2C841%2C842%2C843%2C844%2C845%2C846%2C847%2C848%2C849%2C850%2C851%2C852%2C853%2C854%2C864%2C865%2C866%2C867%2C868%2C869%2C870%2C871%2C872%2C873%2C874%2C875%2C876%2C877%2C878%2C879%2C880%2C881%2C882%2C883%2C884%2C885%2C886%2C887%2C888%2C889%2C890%2C891%2C892%2C893%2C894%2C895%2C896%2C897%2C898%2C899%2C900%2C901%2C902%2C903%2C904%2C905%2C906%2C907%2C908%2C909%2C910%2C911%2C912%2C913%2C914%2C915%2C916%2C917%2C918%2C919%2C920%2C921%2C922%2C923%2C924%2C925%2C926%2C927%2C928%2C929%2C930%2C931%2C932%2C933%2C934%2C935%2C936%2C937%2C938%2C939%2C940%2C941%2C942%2C943%2C944%2C945%2C946%2C947%2C948%2C949%2C950%2C951%2C952%2C953%2C955%2C956%2C957%2C958%2C959%2C960%2C961%2C962%2C963%2C964%2C965%2C966%2C967%2C968%2C969%2C970%2C971%2C972%2C973%2C977%2C978%2C979%2C982%2C983%2C984%2C985%2C986%2C987%2C988%2C989%2C990%2C992%2C993%2C996%2C998%2C999%2C1000%2C1002%2C1004%2C1006%2C1007%2C1008%2C1009%2C1010%2C1011%2C1012%2C1013%2C1014%2C1015%2C1016%2C1018%2C1020%2C1021%2C1022%2C1023%2C1024%2C1025%2C1026%2C1027%2C1028%2C1029%2C1030%2C1031%2C1032%2C1033%2C1034%2C1035%2C1036%2C1037%2C1038%2C1039%2C1040%2C1041%2C1042%2C1043%2C1044%2C1045%2C1046%2C1047%2C1048%2C1049%2C1050%2C1051%2C1052%2C1053%2C1054%2C1055%2C1056%2C1057%2C1058%2C1059%2C1060%2C1061%2C1062%2C1063%2C1064%2C1065%2C1066%2C1067%2C1068%2C1069%2C1070%2C1071%2C1072%2C1073%2C1074%2C1075%2C1076%2C1077%2C1078%2C1079%2C1080%2C1081%2C1082%2C1083%2C1084%2C1085%2C1086%2C1087%2C1088%2C1089%2C1090%2C1091%2C1092%2C1093%2C1094%2C1095%2C1096%2C1097%2C1098%2C1099%2C1100%2C1101%2C1102%2C1103%2C1104%2C1105%2C1106%2C1107%2C1108%2C1109%2C1110%2C1111%2C1112%2C1113%2C1114%2C1115%2C1116%2C1117%2C1118%2C1119%2C1120%2C1121%2C1122%2C1123%2C1124%2C1125%2C1126%2C1127%2C1128%2C1129%2C1133%2C1139%2C1142%2C1143%2C1144%2C1145%2C1146%2C1147%2C1148%2C1149%2C1150%2C1153%2C1154%2C1158%2C1167%2C1168%2C1169%2C1170%2C1171%2C1172%2C1173%2C1174%2C1175%2C1176%2C1177%2C1178%2C1179%2C1180%2C1181%2C1182%2C1183%2C1184%2C1185%2C1186%2C1187%2C1188%2C1189%2C1190%2C1191%2C1192%2C1193%2C1194%2C1195%2C1196%2C1197%2C1198%2C1199%2C1200%2C1201%2C1202%2C1203%2C1204%2C1205%2C1206%2C1207%2C1208%2C1209%2C1210%2C1211%2C1212%2C1213%2C1214%2C1215%2C1216%2C1217%2C1218%2C1219%2C1220%2C1221%2C1222%2C1223%2C1224%2C1225%2C1226%2C1227%2C1228%2C1229%2C1230%2C1231%2C1232%2C1233%2C1234%2C1235%2C1236%2C1237%2C1238%2C1239%2C1240%2C1241%2C1242%2C1243%2C1244%2C1245%2C1246%2C1247%2C1248%2C1249%2C1250%2C1252%2C1253%2C1254%2C1255%2C1256%2C1257%2C1259%2C1260%2C1261%2C1262%2C1264%2C1266%2C1267%2C1268%2C1269%2C1270%2C1271%2C1272%2C1273%2C1274%2C1275%2C1277%2C1278%2C1279%2C1280%2C1282%2C1283%2C1284%2C1285%2C1286%2C1287%2C1288%2C1289%2C1290%2C1291%2C1292%2C1293%2C1294%2C1295%2C1296%2C1297%2C1298%2C1299%2C1300%2C1301%2C1302%2C1303%2C1304%2C1305%2C1306%2C1307%2C1308%2C1309%2C1310%2C1311%2C1312%2C1313%2C1314%2C1315%2C1316%2C1317%2C1318%2C1319%2C1320%2C1321%2C1322%2C1323%2C1324%2C1325%2C1326%2C1329%2C1330%2C1332%2C1333%2C1334%2C1335%2C1336%2C1337%2C1338%2C1339%2C1340%2C1341%2C1342%2C1343%2C1344%2C1345%2C1346%2C1347%2C1348%2C1349%2C1350%2C1351%2C1353%2C1354%2C1355%2C1356%2C1357%2C1358%2C1359%2C1360%2C1361%2C1362%2C1363%2C1364%2C1365%2C1366%2C1367%2C1369%2C1370%2C1372%2C1373%2C1374%2C1375%2C1376%2C1377%2C1378%2C1379%2C1380%2C1381%2C1382%2C1383%2C1384%2C1385%2C1386%2C1387%2C1388%2C1389%2C1390%2C1391%2C1392%2C1393%2C1394%2C1395%2C1396%2C1397%2C1398%2C1399%2C1400%2C1401%2C1402%2C1403%2C1404%2C1405%2C1406%2C1407%2C1414%2C1416%2C1417%2C1418%2C1419%2C1420%2C1421%2C1422%2C1423%2C1425%2C1426%2C1427%2C1428%2C1437%2C1440%2C1441%2C1442%2C1443%2C1444%2C1445%2C1446%2C1447%2C1448%2C1449%2C1450%2C1451%2C1452%2C1453%2C1454%2C1455%2C1456%2C1457%2C1458%2C1459%2C1460%2C1461%2C1462%2C1463%2C1464%2C1465%2C1466%2C1467%2C1468%2C1469%2C1470%2C1471%2C1472%2C1473%2C1474%2C1475%2C1476%2C1477%2C1478%2C1479%2C1480%2C1481%2C1482%2C1483%2C1484%2C1485%2C1486%2C1487%2C1488%2C1489%2C1490%2C1491%2C1492%2C1493%2C1494%2C1495%2C1496%2C1497%2C1498%2C1499%2C1500%2C1501%2C1502%2C1503%2C1504%2C1505%2C1506%2C1507%2C1508%2C1509%2C1510%2C1511%2C1512%2C1513%2C1514%2C1515%2C1516%2C1517%2C1519%2C1520%2C1521%2C1522%2C1523%2C1524%2C1525%2C1526%2C1527%2C1528%2C1529%2C1530%2C1531%2C1532%2C1533%2C1534%2C1535%2C1536%2C1537%2C1538%2C1539%2C1540%2C1541%2C1542%2C1543%2C1544%2C1545%2C1546%2C1547%2C1548%2C1549%2C1550%2C1551%2C1552%2C1553%2C1554%2C1555%2C1556%2C1557%2C1558%2C1559%2C1560%2C1561%2C1562%2C1563%2C1564%2C1565%2C1567%2C1568&time_from=2015-12-01T10%3A15%3A00.000%2B01%3A00&time_to=2015-12-02T10%3A15%3A00.000%2B01%3A00&limit=last
```

504 response appears instead of real data.

**Comment by nowakowski** [comment] 2016-01-04 08:13
@dharezlak 's DAP proxy is impatient and times out before a response is received from DAP. Increase timeout value (for now).

**Comment by mkasztelnik** [comment] 2016-01-04 08:18
Since we have already valid certificate for DAP UI does not use proxy. CORS requests are made directly from the browser into DAP. Nginx timeout is set to 60s so it seems like DAP query takes more than 60s :cry:

**Comment by nowakowski** [comment] 2016-01-04 10:08
Raised to 600s, try it now?

**Comment by mkasztelnik** [comment] 2016-01-04 10:14
It solves 504 issue but not solve "this is toooooooooooooo long" issue. Any approximate date when it will be faster (5 to max 10s is acceptable IMHO)?

**Comment by nowakowski** [comment] 2016-01-04 10:58
@mkasztelnik Working on it; bear with me...

**Comment by nowakowski** [comment] 2016-01-04 10:58
Btw., since the issue is fixed as per report, I suggest closing this ticket (slow queries are a whole different issue).

**Comment by mkasztelnik** [comment] 2016-01-04 10:59
Ok, but please give us a date, when slow queries issue will be solved.

**Comment by nowakowski** [comment] 2016-01-04 15:50
@mkasztelnik I've pushed a temporary fix to both prod and dev. You should see a ~20-fold improvement in DAP response times.

**Closed by nowakowski** 2016-01-04 15:50 UTC
Labels: bug

**Comment by mkasztelnik** [comment] 2016-01-05 09:33
This fix i perfect :dancer:  fibre loading time ~3.5s :heart::heart::heart: - good job :+1:
